version: '3'

services:
  webapp:
    build: ./
    command: ["yarn", "start"]
    ports:
      - 3000:3000
    volumes:
      - ./webapp:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      .env
